### ISSUE TITLE
Were your Timelines Events and LifeSpans ever put in LaTeX style files?

### ISSUE THREAD

**Issue by rickhg12hs** [vitalyrepin/Modern2013#1]
Hello.

Your Timelines Events and LifeSpans in your documents look really good.  Have you ever created LaTeX style files for a package to simplify the use of your timelines?

Best regards.

**Comment by vitalyrepin** [comment]
Hello,

Unfortunately no. I planned to do this but became busy and forgot about this idea.

**Comment by rickhg12hs** [comment]
If you wanted to create the same, or similar timelines, would you repeat what you used before? ... or do you know of another package that you might use?

**Comment by vitalyrepin** [comment]
I have not googled for this subject. But I would definitely take a look into tikz project and its add-ons.

**Comment by rickhg12hs** [comment]
OK, Thanks for your responses.
